# Nombre del usuario de la base de datos
database_user: boeke_user
# Host del servidor de MySQL
database_host: 127.0.0.1
# Puerto del servidor de MySQL
database_port: 3306
# Nombre de la base de datos
database_name: boeke_production
# Contraseña del usuario de la base de datos
database_pass: "my fancy password"

# Depuración activada
debug: true

# Ruta de las cookies
cookie_path: /
# Cookies por https
cookie_secure: false
# Cookies solo accesibles desde http
cookie_http_only: false
# Duración de las cookies
cookie_lifetime: 15 days
# La clave secreta para el cifrado de cookies
secret_key: "here be dragons"
# Salto de contraseña
password_salt: "salt"
# Máximos intentos de conexión
login_max_retries: 6
# Tiempo de bloqueo (en segundos) tras haber superado los intentos máximos
# de conexión
login_block: 600